application: car-hub
version: python
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /tools/?.*
  script: tools.app

- url: /admin/?.*
  script: admin.app
  login: admin

- url: /brian/?.*
  script: brian.app
  login: admin

- url: /cron/?.*
  script: admin.app
  login: admin

- url: /blob/?.*
  script: blob.app
  login: required

- url: /settings/?.*
  script: settings.app
  login: required

- url: /vehicle/?.*
  script: vehicle.app
  login: required

- url: /api/?.*
  script: api.app
  login: required

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"

builtins:
- deferred: on

inbound_services:
- warmup
